# Generated by Django 4.2.3 on 2023-08-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('province', models.CharField(choices=[('SJO', 'San Jose'), ('ALA', 'Alajuela'), ('CAR', 'Cartago'), ('HER', 'Heredia'), ('GUA', 'Guatemala'), ('PUN', 'Puntarenas'), ('LIM', 'Limon')], max_length=11, null=True)),
                ('canton', models.CharField(max_length=75)),
                ('district', models.CharField(max_length=75)),
                ('lngNode', models.CharField(default='-84.0833', max_length=11)),
                ('latNode', models.CharField(default='9.93333', max_length=11)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.division')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
            ],
        ),
    ]
