# Generated by Django 4.2.3 on 2023-08-21 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesPoint', '0002_salespoint_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespoint',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
