# Generated by Django 4.2.3 on 2023-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        ('question', '0004_alter_question_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='division',
        ),
        migrations.AddField(
            model_name='question',
            name='division',
            field=models.ManyToManyField(blank=True, null=True, to='division.division'),
        ),
    ]
