# Generated by Django 4.2.3 on 2023-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        ('question', '0005_remove_question_division_question_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='division',
            field=models.ManyToManyField(blank=True, to='division.division'),
        ),
    ]
